version: '3'
services:
  redis:
    image: 'redis:5.0.3-alpine'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '4001:80'
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - AUTH_REDIRECT_URL_BASE=http://localhost:4001