version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: dev.Dockerfile
    ports:
      - '4001:80'
  client:
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./app:/app
    ports:
      - '3000:3000'
  redis:
    image: 'redis:5.0.3-alpine'
  server:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - '5000:5000'
    environment:
      - AUTH_REDIRECT_URL_BASE=http://localhost:4001